name: Generate PDF manuals

on:
  gollum:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}
          path: repo
      - name: Checkout Wiki
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - name: Install Typst
        uses: typst-community/setup-typst@v4
      - name: Install Pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: 3.8.2.1
      - run: ls -l wiki
      - name: Build PDFs
        run: make -C wiki; cp wiki/*.pdf .
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: manuals
          path: "*.pdf"
