jobs:
name: Generate PDF manuals

on:
  wiki:
    types: 
      - edited
      - created
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-pdfs:
    strategy:
      matrix:
        lang:
          - EN
          - IT
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Wiki
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          path: wiki

      - uses: typst-community/setup-typst@v4
      - uses: docker://pandoc/core:3.5
        with:
          args: >-
            --read=gfm 
            --write=typst 
            -o Manual_${{ matrix.lang }}.typ
            Manual_${{ matrix.lang }}.md

      - run: typst compile Manual_${{ matrix.lang }}.typ Manual_${{ matrix.lang }}.pdf
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: manual-${{ matrix.lang }}
          path: Manual_${{ matrix.lang }}.pdf
